### PR TITLE
Removed type module

### PR DESCRIPTION
**Pull request by maiconcarraro**
React working: 
image

Let me know if that's the only thing that was missing, or which commands to reproduce your error.

### CODE REVIEW

**Comment by LouisBrunner** [comment]
Hi @maiconcarraro,

Thanks a lot for your contribution! 😄 

I don't mind removing it if that's the way forward, but why does it work for other libraries like `react-dnd` ([see here](https://npm-explorer.tk/?p=react-dnd@16.0.1/package.json&selection=6:0-5:0))?

**Comment by maiconcarraro** [comment]
> Hi @maiconcarraro,
> 
> Thanks a lot for your contribution! 😄
> 
> I don't mind removing it if that's the way forward, but why does it work for other libraries like `react-dnd` ([see here](https://npm-explorer.tk/?p=react-dnd@16.0.1/package.json&selection=6:0-5:0))?

Not sure about this npm-explorer link, but if you check their offical github repo I dont see the mention to it: https://github.com/react-dnd/react-dnd/blob/v16.0.0/package.json

**Comment by LouisBrunner** [comment]
@maiconcarraro You are looking at the wrong package.json: https://github.com/react-dnd/react-dnd/blob/main/packages/react-dnd/package.json 😉

**Comment by maiconcarraro** [comment]
> @maiconcarraro You are looking at the wrong package.json: https://github.com/react-dnd/react-dnd/blob/main/packages/react-dnd/package.json 😉

My bad =/ not sure how to help right now, I can take a look later, was using dnd-kit for now since it was an urgent delivery

**Comment by LouisBrunner** [comment]
Hi @maiconcarraro,

Thanks again for this PR!

I found an alternative way to fix this issue (moving to esbuild to avoid babel/webpack wackyness) so I'll be closing this PR.

**Pull request closed without merging**
